# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df0f66ef860c7af85d93259ee8bfd2e5"
name = "discount-beta"
handle = "discount-beta"
application_url = "https://structured-convinced-improved-medium.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://persistent-applies-acquired-document.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://persistent-applies-acquired-document.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://structured-convinced-improved-medium.trycloudflare.com/auth/callback",
  "https://structured-convinced-improved-medium.trycloudflare.com/auth/shopify/callback",
  "https://structured-convinced-improved-medium.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://structured-convinced-improved-medium.trycloudflare.com/api"
subpath = "product"
prefix = "apps"

[pos]
embedded = false
