# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8866f925b9ba7302e6f1537004bc1469"
name = "discount-beta-hp-2"
handle = "discount-beta-hp-2"
application_url = "https://rw-subjects-sb-murder.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rw-subjects-sb-murder.trycloudflare.com/auth/callback",
  "https://rw-subjects-sb-murder.trycloudflare.com/auth/shopify/callback",
  "https://rw-subjects-sb-murder.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
