# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80c7816713770b2fc4ef0febdc7cc9b9"
organization_id = "164642336"
name = "discount-new"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,write_discounts_allocator_functions,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://night-made-essay-joe.trycloudflare.com/api"
subpath = "vol-api"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
