# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a4e521070ed78bb816b9cbf882f1d1c"
name = "Volume Discount"
handle = "volume-discount-107"
application_url = "https://terminology-porcelain-karma-telling.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://terminology-porcelain-karma-telling.trycloudflare.com/auth/callback",
  "https://terminology-porcelain-karma-telling.trycloudflare.com/auth/shopify/callback",
  "https://terminology-porcelain-karma-telling.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
