api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "order-discount"

uid = "3dfee65d-f9a6-6dd6-37e5-f13423d290cf6d229b2f"

type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
